### ISSUE TITLE
[OFStream,OFRunLoop] Notification of OFStream readiness to read, EOF

### ISSUE THREAD

**Issue by JX7P** [ObjFW/ObjFW#112]
It would be useful if notifications of readiness to read and EOF could be received for OFStreams. Perhaps the delegate method/block could accept a parameter indicating the number of bytes available to read in the case of the former.

**Comment by Midar** [comment]
Do you mean something like OFKernelEventObserver? :) That would be the API if you don't want to perform a single async operation on a socket and want something more lowlevel.

Otherwise, you can have a repeating async read that triggers whenever new data is available or EOF reached.

**Comment by Midar** [comment]
As for bytes available: You can on some OSes query the kernel how many bytes it has buffered, but I'm unconvinced this is useful. It would only work for sockets without anything like SSL on top. And it would break as soon as streams are wrapped (think a DEFLATE stream). Often times, you cannot know how many bytes are available without trying to read as many bytes as possible. And even then you can't know really, as reading everything from the buffer might just mean more data can now be read into the buffer.

**Comment by JX7P** [comment]
Thanks for the response, I think here an OFKernelEventObserver will be the most useful for me. It does seem unfortunately that there is no portable way of determining how much is available to read from a socket.
