### ISSUE TITLE
[OFStream] atEndOfStream - read()/recv() returning 0 shouldn't mean stream is permanently atEnd

### ISSUE THREAD

**Issue by JX7P** [ObjFW/ObjFW#113]
Concrete implementations of OFStream set themselves `atEndOfStream` when read()/recv() returns 0. This is abstracted as a permanent condition, but it's not necessarily so. 
If I `readDataUntilEndOfStream`, from a socket, for example, I expect that it will read all the data that can be read presently. Later, if more data arrives on the socket, I should be able to read that with `readDataUntilEndOfStream`.

**Comment by Midar** [comment]
Ah, it looks like you want to -[readIntoBuffer:length:] for your use case. readDataUntilEndOfStream is basically meant to do that: Read the entire rest of the stream until EOF is reached. It's mostly used for files if you have some header and then want the entire remaining thing as data. Think of a BMP file with headers first and then followed by data.

In theory it would be possible to have a readData that reads whatever is available - but recreating this data object on every read would be wasteful.

**Comment by Midar** [comment]
Also, there seems to be a misunderstanding here of how sockets work: A read of length 0 is to indicate that the socket was closed. For select() and friends, this is indicated as the socket being ready for reading, and every read returning 0 bytes.

Closing as invalid as there's nothing to do here - we can't change how BSD sockets work :).
