### ISSUE TITLE
[OFProcess] posix_spawnp failure sets an unspecified PID, which `- close` attempts to kill

### ISSUE THREAD

**Issue by JX7P** [ObjFW/ObjFW#114]
The POSIX implementation of OFProcess uses posix_spawnp to spawn a process. If posix_spawnp fails, however, it sets the value pointed to by its first argument to an undefined value - not necessarily -1 as fork() does. So if posix_spawnp fails here: https://github.com/ObjFW/ObjFW/blob/f3aea8ea14814ee3f3fb3d4ada89ecb70dc54ddd/src/platform/posix/OFProcess.m#L180-L183
then the value of _pid is undefined. When this OFProcess's `- close` method is consequently invoked after it throws, it then tries to kill this undefined PID:
https://github.com/ObjFW/ObjFW/blob/f3aea8ea14814ee3f3fb3d4ada89ecb70dc54ddd/src/platform/posix/OFProcess.m#L368
Explicitly setting _pid to -1 if posix_spawnp fails will resolve this.

**Comment by Midar** [comment]
The manpage seems to document that pid is not touched at all. However, you found a more generic problem here: This should be set to -1 in init before anything that could fail could trigger an exception and hence the deallocation of the object in a state where it is still 0.

**Comment by Midar** [comment]
Should be fixed by 82d73345 which takes care of the more generic problem. Thanks a lot for finding and reporting! :)
