### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by fuzzbop** [ObjFW/ObjFW#115]
I have created and uploaded a PKGBUILD to the AUR for Arch Linux. It is my first package so I hope everything is correct in it (I successfully built the pkg in a chroot, so in theory it should be)

It is a -git so it will allways pull latest from git and build. unless anything major changes in your compilation methods it should be self sustaining I think (again this is my first package). 

If anyone here would like to maintain/let me know if I done anything wrong. PLEASE do

**Comment by Midar** [comment]
That's great! :)

I think there were several other AUR packages before:
https://github.com/mirar-smp/AUR_objfw-git
I can't find any others right now. But maybe it has things you can steal :).

Is https://aur.archlinux.org/packages/objfw-git/ yours? It has your name at least :).
Some suggestions: Maybe depend on Clang to make all modern ObjC features available? I think Clang is available for all architectures Arch Linux supports? The the license is actually QPL or GPL2 or GPL3 :).

**Comment by fuzzbop** [comment]
on it!

**Comment by fuzzbop** [comment]
This oversight fixed the problem I was having with the package I even started this venture for!! thank you so much!

**Comment by Midar** [comment]
Also, the official upstream URL is https://objfw.nil.im/ :) But cloning from the GitHub mirror is fine.

Out of curiosity, which package is that? :)

**Comment by fuzzbop** [comment]
I just tried swapping to the official upstream and it was very slow compared to the github.
I fixed up those depends and everything built fine I will be pushing the changes in just a moment.
The package (still working on it) is for [mkxp-z](https://github.com/inori-z/mkxp-z) and the clang dependency makes perfect sense with it being required to build with clang lol

**Comment by Midar** [comment]
Yeah, that's why I said using the git mirror from GitHub is fine, but the homepage could point to https://objfw.nil.im/ :). Or is there no differentiation between homepage and repo URL in AUR?

I was thinking about something like here:
https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=blob;f=objfw-git/Makefile;h=edd3efcb65504ef48cd78b763da9c1985b104ce8;hb=HEAD

**Comment by fuzzbop** [comment]
It should be fixed now!

**Comment by Midar** [comment]
Thx for doing this! Closing this bug now then :).

Minor nit: Description could be "Objective-C" instead of "Objective C", but that's a really minor thing.
