### ISSUE TITLE
ObjFW and llvm-mingw

### ISSUE THREAD

**Issue by EddaAkikusa** [ObjFW/ObjFW#121]
llvm-mingw uses `lld` as default linker instead of GNU `ld`, which doesn't support `--allow-multiple-definition` flag when targeting Windows, so I can't `configure` to build ObjFW using such toolchains.
Parts of `config.log`:
```
## ----------- ##
## Core tests. ##
## ----------- ##

configure:2647: checking build system type
configure:2661: result: arm-apple-darwin20.2.0
configure:2681: checking host system type
configure:2694: result: i686-w64-mingw32
configure:2901: checking for i686-w64-mingw32-clang
configure:2917: found /opt/llvm-mingw/bin//i686-w64-mingw32-clang
configure:2928: result: i686-w64-mingw32-clang
configure:2997: checking for Objective C compiler version
configure:3006: i686-w64-mingw32-clang --version >&5
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: /opt/llvm-mingw/bin
configure:3017: $? = 0
configure:3006: i686-w64-mingw32-clang -v >&5
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: /opt/llvm-mingw/bin
configure:3017: $? = 0
configure:3006: i686-w64-mingw32-clang -V >&5
clang-11: error: argument to '-V' is missing (expected 1 value)
clang-11: error: no input files
configure:3017: $? = 1
configure:3006: i686-w64-mingw32-clang -qversion >&5
clang-11: error: unknown argument '-qversion'; did you mean '--version'?
clang-11: error: no input files
configure:3017: $? = 1
configure:3037: checking whether the Objective C compiler works
configure:3059: i686-w64-mingw32-clang    -Wl,--allow-multiple-definition conftest.m  -lversion >&5
lld: error: unknown argument: --allow-multiple-definition
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3063: $? = 1
configure:3101: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ObjFW"
| #define PACKAGE_TARNAME "objfw"
| #define PACKAGE_VERSION "1.1-dev"
| #define PACKAGE_STRING "ObjFW 1.1-dev"
| #define PACKAGE_BUGREPORT "js@nil.im"
| #define PACKAGE_URL ""
| #define OBJFW_VERSION_MAJOR 1
| #define OBJFW_VERSION_MINOR 1
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3106: error: in `/Users/eddaakikusa/ObjFW/i86-pc':
configure:3108: error: Objective C compiler cannot create executables
See `config.log' for more details
```

**Comment by Midar** [comment]
Please follow the instructions in https://github.com/objfw/objfw#windows - this is the only supported toolchain, as the general state of compilers on Windows is … well, very buggy. This is the only one that is known to work, not even regular MinGW64 works due to compiler bugs. The usual result of using anything else will be that exceptions don't work etc. Even with that one, there is still corner cases in which exceptions + ARC breaks. Rather than spend the time supporting yet another Windows toolchain with another set up bugs, I'd rather spend the time to fix that corner case and have at least one toolchain that works well.

**Comment by Midar** [comment]
Now that I think of it: Just removing that flag would not work anyway, as some helper methods exist with the same name in ObjFW and the runtime. It would require renaming those in the runtime. But that might be a good idea anyway, so I'm gonna do that - but no promises that this magically makes it work with your toolchain ;). But please report back once I did to let me know if it works.

**Comment by EddaAkikusa** [comment]
No, I can't even build the ObjFW itself due to wrong AS flags.
```
Entering directory src.
Entering directory runtime.
Entering directory lookup-asm.
clang-11: error: unsupported option '--32'
clang-11: error: assembler command failed with exit code 1 (use -v to see invocation)
Failed to compile lookup-asm.S (lib)!
make[7]: *** [lookup-asm.lib.o] Error 1
make[6]: *** [all] Error 2
make[5]: *** [lookup-asm] Error 2
make[4]: *** [all] Error 2
make[3]: *** [runtime] Error 2
make[2]: *** [all] Error 2
make[1]: *** [src] Error 2
make: *** [all] Error 2
```

**Comment by Midar** [comment]
--32 is not coming from ObjFW (you can grep the source - it's not in there). So your your build environment is adding that somewhere while it cannot handle it → *Your build environment is broken*. Please follow these instructions to get a working build environment that has a working Clang: https://github.com/objfw/objfw#windows

**Comment by EddaAkikusa** [comment]
Alright.

**Comment by Midar** [comment]
Did that work for you?

**Comment by EddaAkikusa** [comment]
Yes, it works.
