### ISSUE TITLE
amiga-gcc, NDK3.2 and ObjFW

### ISSUE THREAD

**Issue by acf** [ObjFW/ObjFW#122]
(sorry its on github but the homepage seems to be down)

I have a working installation of amiga-gcc using NDK3.2 on my intel Mac.  I cloned and configured ObjFW according to the instructions.  

When I try `make check` or `make install` I get the following error messages and I'm not sure how best to work around them.  Any suggestions appreciated, as I'm keen to start using some ObjC on the amiga :-)

```
acf@Touchbook16 ObjFW % make check
Entering directory src.
Entering directory runtime.
Entering directory lookup-asm.
Successfully compiled lookup-asm.S.
Successfully linked lookup-asm.amigalib.a.
Leaving directory lookup-asm.
In file included from /opt/amiga/m68k-amigaos/ndk-include/inline/stubs.h:14:0,
                 from /opt/amiga/m68k-amigaos/ndk-include/inline/macros.h:23,
                 from /opt/amiga/m68k-amigaos/ndk-include/inline/exec.h:16,
                 from /opt/amiga/m68k-amigaos/ndk-include/proto/exec.h:13,
                 from amiga-library.m:26:
/opt/amiga/m68k-amigaos/ndk-include/intuition/classes.h:50:3: error: conflicting types for 'Class'
 } Class;
   ^~~~~
In file included from amiga-library.m:18:0:
ObjFWRT.h:85:28: note: previous declaration of 'Class' was here
 typedef struct objc_class *Class;
                            ^~~~~
Failed to compile amiga-library.m (Amiga lib)!
make[4]: *** [amiga-library.amigalib.o] Error 1
make[3]: *** [all] Error 2
make[2]: *** [runtime] Error 2
make[1]: *** [all] Error 2
make: *** [src] Error 2


```

**Comment by Midar** [comment]
Sorry, I missed this because I was not checking GitHub, and GitHub consistently fails sending me an e-mail on a new bug report.

This sounds related to the 3.2 NDK. There is a bug about this at the amiga-gcc project: https://github.com/bebbo/amiga-gcc/issues/222

**Comment by acf** [comment]
Heh yes it was me that started that thread.   I'm a bit confused because the same `intuition/classes.h`, containing a `Class` struct exists in the 3.9 NDK so I'd assume it would clash there as well, no ?

**Comment by acf** [comment]
Did a bit of tracing and I see indeed a different include chain on the two NDKs.   Ah well, thanks anyway.
