### ISSUE TITLE
[Question] Call +load method of ObjC class category

### ISSUE THREAD

**Issue by GunGraveKoga** [ObjFW/ObjFW#37]
Apple Objective C Runtime support call to +load method for class category, but seems ObjFW does not support this ability. Is this possible to add call +load method for class categories?

**Comment by Midar** [comment]
I can see the use cases for this - even if Apple would not provide it. Seems like a good addition.

**Comment by Midar** [comment]
A similar issue has been added in Fossil: https://objfw.nil.im/tktview/665fee1f7468ea796bbe37b654c231b0771b0ed6
