### ISSUE TITLE
[runtime] add support of imp_implementationWithBlock

### ISSUE THREAD

**Issue by GunGraveKoga** [ObjFW/ObjFW#49]
Apple ObjC Runtime have functions imp_implementationWithBlock, imp_getBlock, imp_removeBlock which allow to create implementation of class methods at runtime via Blocks-closuer.
It will be great to get those features in ObjFW

**Comment by Midar** [comment]
These require a platform-specific trampoline. I'm not sure if it's a good use of my time to write one for each platform currently supported, as I only see limited use of it. If you can come up with a good use for it, I might change my mind, though.

**Comment by GunGraveKoga** [comment]
Main reason to implement imp_implementationWithBlock is support of dynamic class creation at runtime, via objc_{allocate,register}ClassPair
But You actually right about hard work for asm-implementation of trampolines for every supported platform.
I solved my needs for cast block to pure C function via libffi.
I was wrote wrapper-class similar to std::function which store ObjC Block and generate libffi-closure with necessary function.
For now i can cast ObjC Block to pure C function and call it without passing block-pointer to function.
Next step try to create closure with ObjC object and its selector, its will be useful for many C-libraries which use callbacks without user data as arguments.

**Comment by GunGraveKoga** [comment]
Firs implementation of libffi wrapper  https://github.com/GunGraveKoga/FFIClosure

**Comment by Midar** [comment]
Ah, good idea having it as a 3rd party library! :)
Feel free to link it in the wiki!
