### ISSUE TITLE
[OFStream] tryReadTillDelimiter:encoding: does not store data in case of exception

### ISSUE THREAD

**Issue by GunGraveKoga** [ObjFW/ObjFW#57]
method tryReadLineWithEncoding: stores data received via lowlevelReadIntoBuffer:length method in case of invalid encoding error, but method tryReadTillDelimiter:encoding: does not implement this action

**Comment by Midar** [comment]
Sorry for the long delay - I don't seem to get notifications about new issues. This should be fixed now.
