### ISSUE TITLE
Build instructions for MorphOS

### ISSUE THREAD

**Issue by mdbergmann** [ObjFW/ObjFW#58]
Would be great if you could write a few lines about this in the readme.

Thanks.

**Comment by Midar** [comment]
The same as for any other OS: Just run `./autogen.sh` and `./configure` :).

clang support on MorphOS is still buggy, so it might be necessary to run `./configure OBJC=ppc-morphos-gcc-5` until a new SDK release to avoid clang being picked up by the configure script.

**Comment by mdbergmann** [comment]
Well, it doesn't seem to be that simple:
```
Work:DevelAdd/Sources/objfw> autogen.sh
Work:DevelAdd/Sources/objfw> ./configure
./configure: Unbekannter Befehl
Work:DevelAdd/Sources/objfw> configure
configure: error: build-aux/m4/buildsys.m4 is newer than configure! Run autoreconf!
Work:DevelAdd/Sources/objfw> autoreconf
Work:DevelAdd/Sources/objfw> configure
configure: error: build-aux/m4/buildsys.m4 is newer than configure! Run autoreconf!
Work:DevelAdd/Sources/objfw> configure OBJC=ppc-morphos-gcc-5
configure: error: build-aux/m4/buildsys.m4 is newer than configure! Run autoreconf!
```

**Comment by Midar** [comment]
Seems like dates on some files are wrong.

Try downloading https://github.com/ObjFW/ObjFW/archive/master.tar.gz.
The following should work then:
```
tar xfvz ObjFW-master.tar.gz
cd ObjFW-master
autogen.sh
configure OBJC=ppc-morphos-gcc-5
make
make install
```

**Comment by mdbergmann** [comment]
yep, MorphOS 3.10 with the latest SDK.

'configure OBJC=ppc-morphos-gcc-5 --disable-amiga-lib' now bails out with:
```
checking for exception type... unknown
configure: error: Exception type not detected!
```

**Comment by mdbergmann** [comment]
Well, there is actually more:

configure: WARNING: objc/objc.h: present but cannot be compiled
configure: WARNING: objc/objc.h:     check for missing prerequisite headers?
configure: WARNING: objc/objc.h: see the Autoconf documentation
configure: WARNING: objc/objc.h:     section "Present But Cannot Be Compiled"
configure: WARNING: objc/objc.h: proceeding with the compiler's result
configure: WARNING:     ## --------------------------- ##
configure: WARNING:     ## Report this to js@heap.zone ##
configure: WARNING:     ## --------------------------- ##
checking for objc/objc.h... no
checking which Objective C runtime to use... ObjFW runtime
checking whether -fobjc-runtime=objfw is supported... no
checking for exception type... unknown
configure: error: Exception type not detected!

**Comment by Midar** [comment]
Hm, that sounds like something with the compiler is wrong. Can you please attach your `config.log` file?

**Comment by mdbergmann** [comment]
OK, here is the config.log.
I see there are some configure errors regarding missing confdevs.h.
But I can't make much sense out of it.
[config.log](https://github.com/ObjFW/ObjFW/files/2034051/config.log)

**Comment by Midar** [comment]
Ah, this is a broken compiler indeed. Or, to be more precise, it's broken because of a broken ixemul.library that has broken pipes. You can work around this by removing the following line from configure.ac:

```
AX_CHECK_COMPILER_FLAGS(-pipe, [OBJCFLAGS="$OBJCFLAGS -pipe"]) 
```

**Comment by Midar** [comment]
Is this solved?

**Comment by mdbergmann** [comment]
I‘m on vacation ATM. Will check next week.

**Comment by mdbergmann** [comment]
OK, it builds now but 'make' doesn't finish due to some failing tests.
However this issue can be closed.

Should the problem with pipe be reported to the MorphOS developers?

**Comment by Midar** [comment]
They are aware and the 3.11 will fix it.

As for the failing test, this used to work on 3.9, so I guess this is a regression for 3.10. I'll see if I can create a minimal test case, so that hopefully this can be fixed with 3.11 as well.

**Comment by Midar** [comment]
MorphOS 3.11 has been released and should fix the issue. Does this now work for you? If so, please close.

**Comment by mdbergmann** [comment]
Ah, I thought you would close, because the workaround already worked.
