### ISSUE TITLE
Can I build ObjFW using Clang/C2?

### ISSUE THREAD

**Issue by CNAmira** [ObjFW/ObjFW#60]
According to [README-WINDOWS.md](https://github.com/ObjFW/ObjFW/blob/master/README-WINDOWS.md) I've have to install MSYS2 and several dependences if I want to build on Windows.
From MSVC 2015 Microsoft has provided a optional component named Clang/C2, it is a modified version of Clang which use MSVC's backend instead of LLVM.
It is tested that it can compile and build objc and objc++ programs and link to ObjFW runtime built by MSYS2, so I'm wondering if I can build ObjFW entirely using Clang/C2?

**Comment by Midar** [comment]
I am not aware of what Clang/C2 exactly is, so I cannot tell. I suggest you just give it a try and report back :).

**Comment by CNAmira** [comment]
Clang/C2 mostly acts as Clang but it uses MSVC's backend and MSVC's tools(linker, sdk, etc.).
The main problem is that it produces MSVC-compatible binaries, so GNU binutils cannot be used with Clang/C2, and the configure script won't work because it cannot produce a working executable program in Msys2 environment.

发自我的 iPhone

**Comment by Midar** [comment]
Is this freely available somewhere? Then I could have a look at it.

**Comment by CNAmira** [comment]
Yes, Visual Studio 2015 Community Edition and newer have an option to install it.

**Comment by CNAmira** [comment]
I think Microsoft is deprecating Clang/C2 because it hasn't received any update since 2016. LLVM has officially provided new binaries which can be integrated into MSVC, and function as Clang/C2 but use LLVM backend instead, it should be compatible with Clang/C2.
So if ObjFW can be compiled with Clang + MSVC, it will also be able to be compiled with Clang/C2.

发自我的 iPhone

**Comment by Midar** [comment]
I don't really intend to support building via an MSVC project. I just dropped the Xcode project a while ago because it was too much hassle to maintain two build systems. Are there any advantages of using Clang/C2 or MSVC rather than building via MSys2?

**Comment by CNAmira** [comment]
I don't think it really needs a separate MSVC project. The MSVC's 'native' compiler `cl` itself won't compile any Objective-C code, only with LLVM's clang or Clang/C2, both them are GNU compatible compiler and can be used with MSYS and GNU Autotools. I think it only needs some tweaks to the build system and won't affect other target.

**Comment by CNAmira** [comment]
Clang/C2 seems to be removed in recently Visual Studio, no need anymore.

**Comment by Midar** [comment]
Ok, thanks for the update! :) Glad I did not waste too much time on this then.
