### ISSUE TITLE
Using ObjFW with Swift

### ISSUE THREAD

**Issue by CNAmira** [ObjFW/ObjFW#61]
I'm using ObjFW with Swift, and I found an incompatible issue.
The second parameter of `of_application_main` is type of `UnsafeMutablePointer<UnsafeMutablePointer<UnsafeMutablePointer<Int8>>>`(aka `char *_Nonnull *_Nonnull[_Nonnull]`). However, the only method to get launch arguments in Swift is using `CommandLine` class, its class member `unsafeArgv` is mostly equal to C-style `argv`, but it has the type `UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>`(aka `char *_Nullable *_Nonnull[_Nonnull]`), which is incompatible with `of_application_main`'s parameter.
I haven't found a macro or `attribute` that can determine whether the header is used by Objective-C compiler or Swift compiler, I have to make a bridge function to make it compile without fails temporarily.

**Comment by Midar** [comment]
Hm, I guess it's marked nullable because argv is defined to be terminated with a NULL. Fixed, thanks for reporting!
