### ISSUE TITLE
Content of directory broken for Windows

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#63]
Content of directory broken for Windows - autoreleased file string wrongly released:
Patch to fix it:

diff -rupN original/src/OFURLHandler_file.m new/src/OFURLHandler_file.m
--- original/src/OFURLHandler_file.m	2019-02-25 12:12:53.000000000 +0300
+++ new/src/OFURLHandler_file.m	2019-02-01 15:47:25.000000000 +0300
@@ -829,7 +829,11 @@ setSymbolicLinkDestinationAttribute(of_m
 				continue;
 
 			file = [OFString stringWithUTF16String: fd.cFileName];
-            [files addObject: file];
+			@try {
+				[files addObject: file];
+			} @finally {
+				[file release];
+			}
 		} while (FindNextFileW(handle, &fd));
 
 		if (GetLastError() != ERROR_NO_MORE_FILES)

**Comment by winnydows** [comment]
Link to patch:
https://www.dropbox.com/s/sz8xooxrq98ukmx/objfw-filemanager-fix.diff?dl=0

**Comment by Midar** [comment]
Thanks for the report! This is fixed now. I went with a different fix, though.
