### ISSUE TITLE
Safe delete functions for Windows

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#64]
For Windows much safer using native and compatible delete functions: RemoveDirectoryW DeleteFileW, because _wrmdir, _wunlink may be broken in some mingw builds.

Simple patch:
https://www.dropbox.com/s/6ad32ya77fs4jtx/objfw-file-io-fix.diff?dl=0

**Comment by Midar** [comment]
Sorry for the late response - I didn't get a notification.

Do you have any details about the broken _wrmdir or _wunlink?

**Comment by winnydows** [comment]
Can't reproduce with latest objfw update. Probably it was echo from wrong release autoreleased object fixed yesterday. Can be closed.

**Comment by Midar** [comment]
Thanks for double-checking - using the W functions instead of the _w functions would have been annoying, as these do not set errno so that I would have needed to map all errors to errnos manually, similar to how I do it on AmigaOS. But please reopen this if it indeed becomes a problem.
