### ISSUE TITLE
of_log crash in window applications for Windows

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#65]
of_log function used for debug or for console messages. This function call may be in window applications also (be any reason) and if use this function in GUI applications (link with -mwindows = run without console window) app will crash. Latest objfw crash after message: Filed to write 87 bytes (after 0 bytes written) to an object of type OFStdIOStream: Bad file descriptor.

I know use of_log in GUI useless, but function may be for debug reason. For example printf don't crash GUI applications.

**Comment by Midar** [comment]
The reason for this might be that ObjFW uses GetStdHandle(). Maybe this fails if there is no console. of_log() writes to of_stderr, and of_stderr needs a console because it does output and input conversion, so that both, writing a UTF-8 encoded string, but also writing binary to a redirected file, work properly. However, in OFStdIOStream_Win32Console.m, there's the following that should make it work:
```
                /* Not a console: Treat it as a regular OFStdIOStream */
                if (!GetConsoleMode(_handle, &mode))
                        object_setClass(self, [OFStdIOStream class]);
```
Can you see if this branch gets taken? Does replacing the if with if (1) fix it?

**Comment by winnydows** [comment]
This block work fine, app crash in OFStdIOStream (with auto object_setClass and with force).
Crash at OFStdIOStream line 112 - of_stderr writeFormat:.

**Comment by winnydows** [comment]
Crash in OFStream:writeBuffer:. Probably of_stderr must be nil in GUI mode.

**Comment by Midar** [comment]
I spent some time looking into this. It seems that GetDefaultHandle() returns a valid handle. So I don't see how I can detect the presence of it not being there, as apparently it is there, it's just that writing to it fails.

That said, ObjFW itself never uses of_log on its own or writes to of_std{out,err}. Is there a reason you are calling of_log() in a GUI app, anyway? And what way is there to figure out there's no terminal?

**Comment by winnydows** [comment]
Reason is same as in NSLog - debug application. I know this problem and always remove of_log lines in debug, but very simple forget this. For me its's not a problem. 
But if ObjFW can easy detect console less mode, why not just ignore messages if this mode detected (for windows)?

**Comment by winnydows** [comment]
Why of_log is simple - no problems with unicode, fine work in XCode, fine work in console on windows (even with GUI application) - I don't remove console for debug mode (debugging cross platform app in windows may be very tricky).

**Comment by Midar** [comment]
I see - so you run the application in a terminal to debug, and then it does ouput things, but in GUI mode, you just want the output discarded.

Is there maybe something like syslog on Windows?

I'm also looking into getting the fd from stderr and stdout via _fileno, to see if that helps in detecting it.

**Comment by winnydows** [comment]
May be exist some logging alternative, but its not need for GUI applications. Just don't crash app. Skip is very good solution for this case. I spend few days understand why app crash in random places, when first time know what its of_log. May be some developers get same.

**Comment by Midar** [comment]
This is fixed now by using _fileno on std{in,out,err}. Apparently, this fails when there is no console, so this it now only creates of_std{in,out,err} if _fileno on std{in,out,err} succeeded.

**Comment by winnydows** [comment]
I know You prefer perfect solution, but I prefer simple solution, this hack work without any problem:

`
@interface OFStdIOStream_HiddenConsole : OFStdIOStream
@end

@implementation OFStdIOStream_HiddenConsole
-(size_t)writeFormat: (OFConstantString *)format, ... {
    return 0;
}
@end

/* Not a console: Treat it as a regular OFStdIOStream */
		if (!GetConsoleMode(_handle, &mode))
			object_setClass(self, [OFStdIOStream_HiddenConsole class]);`

**Comment by Midar** [comment]
Nope, that’s not a solution. That will break redirecting output to a file AFAIU. It will also only work for writeFormat:, which is by no means guaranteed to be used. Additionally, returning just 0 can easily result in an infinite loop at a call site.

In any case, the way I fixed this, it should always work. It not, please reopen.

**Comment by winnydows** [comment]
Confirmed - work fine now - thanks a lot.
