### ISSUE TITLE
OFFileManager attributesOfItemAtPath can't read remote file path 

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#66]
Windows version of OFFileManager attributesOfItemAtPath can't read remote file path. For example: \\\Mac\Files\info.txt

Exception: Failed to retrieve attributes for item <OFURL: file:///C:/Users/winny/Mac/Files/info.txt>: No such file or directory
Wrongly added by objfw core local path prefix: C:/Users/winny/ ?

fileExistsAtPath return true for \\\Mac\Files\info.txt
Same reaction for attributesOfItemAtURL.

wxWidgets method work fine:
```
wxStructStat strucStat;
wxStat([path wxString], &strucStat);
return strucStat.st_size;
```

**Comment by winnydows** [comment]
Path start with double slash (text engine of github eat first slash).

**Comment by Midar** [comment]
This is a general problem when translating a file path to a file URL. Is there even a standard way of converting those to file URLs?

**Comment by Midar** [comment]
Apparently, there is: \\foo\bar as a file URL is file://foo/bar.

There's currently no support for remote URLs in OFString+PathAdditions_DOS and no support for file URLs with a host.

**Comment by winnydows** [comment]
But why fileExistsAtPath work fine ?

**Comment by Midar** [comment]
It really shouldn't, as it converts it to a URL and then uses fileExistsAtURL:.

**Comment by winnydows** [comment]
My bad - I use wxFileExists([path wxString]); as replacement OFFileManager fileExistsAtPath.
Reason [[self defaultManager] fileExistsAtPath:path]; freeze on macOS some times, without any reason.

[[self defaultManager] directoryExistsAtPath:path];
Return NO for disks even if disk path exists, so for folders I use wxDirExists replacement too.

**Comment by Midar** [comment]
[self defaultManager]? What are you doing? Are you adding a category on OFFileManager?

Do you have a test case for the hanging on OS X? I'd be interested in debugging and fixing that.

I can add support for remote paths on Windows.

**Comment by Midar** [comment]
I just added UNC support in 1d8a0602 - let me know if this looks reasonable and works.

**Comment by winnydows** [comment]
Category used for extensions, but OFFileManager can't be just extended - many functions fail on Windows. So I use my @interface XVFileManager : OFFileManager - combo from ObjFW + wxWidtgets + my custom functions unimplemented in ObjFW. For example useful creationDate get/set unimplemented in ObjFW.

Network paths fixed in latest update - thanks a lot.
About other OFFileManager bugs - I create new issues threads when retest all problems.
