### ISSUE TITLE
OFFileManager:directoryExistsAtPath c:\ return NO

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#67]
OFFileManager:directoryExistsAtPath return false for any disks on Windows. From logic point disk == first folder and must return true as wxWidgets do.

**Comment by Midar** [comment]
Hm, is that technically a directory? I would think technically this is a drive? Do you know of any MS documentation defining which it is?

**Comment by winnydows** [comment]
Do you mean we need one more function for windows only driveExitstsAtPath ? It's not funny.

**Comment by Midar** [comment]
I don’t have any Windows nearby, so I cannot year, but my guess is that Windows does not classify it as a directory, and hence it returns false. Does fileExistsAtPath: return true? This is supposed to return true it it exists at all, not only for regular files. If this returns true but directoryExistsAtPath: false, it means Windows considers it not a directory.

**Comment by winnydows** [comment]
fileExistsAtPath return false also, for all variants: c: c:\ c:/, same as directoryExistsAtPath.

**Comment by winnydows** [comment]
Just now tested with WinAPI and it work fine be default:

```
DWORD ret = GetFileAttributes(strPath.t_str());
        if (ret == INVALID_FILE_ATTRIBUTES) {
            return NO;
        
        if (ret & FILE_ATTRIBUTE_DIRECTORY)
            return YES;
```

**Comment by Midar** [comment]
I think it might make sense to change the way path components work on Windows. It currently considers a path like c:\foo\bar to consist of "c:", "foo", and "bar" - I think it should instead be "c:\", "foo" and "bar". Then it can treat C:\ as separate and still keep the \ etc.

**Comment by Midar** [comment]
The paths are now handled correctly. Interestingly, stat() on C:\ works correctly on MS-DOS. I wonder why Windows handles it differently.

**Comment by Midar** [comment]
This is fixed now.
