### ISSUE TITLE
Any plan to support HTTP/2?

### ISSUE THREAD

**Issue by Frozen-Tofu** [ObjFW/ObjFW#73]
Some websites only accept HTTP 2 request for security, it seems that  ObjFW is not ready for that, it's there any plan to support HTTP/2 request?

**Comment by Midar** [comment]
Can you give an example that *only* supports HTTP/2? Only supporting HTTP/2 seems to be against the standard itself.

Considering just how insanely complex HTTP/2 is, I'd say it's unlikely to be implemented.

**Comment by Frozen-Tofu** [comment]
Apple Push Notification Service will only accept HTTP/2 connection when using token-based authentication.

**Comment by Midar** [comment]
Hm, HTTP/2 is very complex, and I think there are not many other use cases for it. Maybe ObjC/ObjFW bindings for nghttp2 would be a better idea? https://nghttp2.org/

**Comment by Midar** [comment]
Closing for now due to inactivity. Feel free to reopen if there's new arguments for implementing HTTP/2.
