### ISSUE TITLE
OFBytesValue and packed struct

### ISSUE THREAD

**Issue by Frozen-Tofu** [ObjFW/ObjFW#74]
If a `struct` is packed, OFBytesValue will contain garbage value, and we will never get the correct value from it.

**Comment by Midar** [comment]
There is unfortunately no way around it: There is no type encoding for packed structs: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html#//apple_ref/doc/uid/TP40008048-CH100

I'd suggest to store it as OFData instead, so you can use sizeof to get the size in bytes and ignore any ObjC encoding.

**Comment by Midar** [comment]
Closing for now. Feel free to reopen if there's anything to add.
